- name: GitHub-Profile-Summary-Cards
  # You may pin to the exact commit or the version.
  # uses: vn7n24fzkq/github-profile-summary-cards@014cfbe8de19ef2fbcb5bda6b7b05eaae045ee3c
  uses: vn7n24fzkq/github-profile-summary-cards@v0.2.6
  with:
    # GitHub username
    USERNAME: # default is ${{ github.repository_owner }}
